runtime: go112
service: chrome-storage-dev

instance_class: F1

env_variables:
    ORIGIN_TRIAL_TOKEN: AnYoFgLduOkDSyMsygpD9BWgPfRP+WB3XF3p7R9yzPP3deCTWmx/93tZqSW/6PCbHjb0Z2sllfDGSWFdNm9hawkAAAB8eyJvcmlnaW4iOiJodHRwczovL2Nocm9tZS1zdG9yYWdlLWRldi1kb3Qtb3lpcHRvbmctY2hyb21lLmFwcHNwb3QuY29tOjQ0MyIsImZlYXR1cmUiOiJOYXRpdmVGaWxlU3lzdGVtIiwiZXhwaXJ5IjoxNTg2OTk2NzA2fQ==,AgV2oVFHzGyiKsMgdrjRIkL1EVH49wrcrkp1s84Rsl3eUC72wsU4eWXDDd+/jklVAJWWW0vQgRvQxTLWZEhimAEAAAB9eyJvcmlnaW4iOiJodHRwczovL2Nocm9tZS1zdG9yYWdlLWRldi1kb3Qtb3lpcHRvbmctY2hyb21lLmFwcHNwb3QuY29tOjQ0MyIsImZlYXR1cmUiOiJOYXRpdmVGaWxlU3lzdGVtMiIsImV4cGlyeSI6MTU4OTkyNjcwNn0=
handlers:
        - url: /.*
          script: auto
          secure: always
          redirect_http_response_code: 301
