runtime: go112
service: chrome-storage

instance_class: F1

handlers:
        - url: /
          static_files: static/index.html
          upload: static/index.html
        - url: /(.*\.(css|js|html))$
          static_files: static/\1
          upload: static/.*\.(css|js|html)$
        - url: /.*
          script: auto
